import pdfParse from 'pdf-parse';
import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';
dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

/**
 * @typedef {Object} ResumeData
 * @property {string[]} skills           - Technical and soft skills found
 * @property {string[]} suggestedRoles   - AI-suggested job titles to search for
 * @property {string}   keywords         - Comma-separated keyword string for embedding
 * @property {string}   experienceLevel  - junior | mid | senior | lead | executive
 * @property {string[]} jobTitles        - Job titles held (from resume history)
 * @property {string[]} locations        - Locations mentioned in resume
 * @property {string}   summary          - Short professional summary generated by AI
 */

// ---------------------------------------------------------------------------
// PDF → plain text
// ---------------------------------------------------------------------------
async function extractText(resumeInput) {
  if (Buffer.isBuffer(resumeInput)) {
    try {
      const pdfData = await pdfParse(resumeInput);
      return pdfData.text;
    } catch (err) {
      console.error('Error parsing PDF:', err);
      throw new Error('Could not parse the provided PDF file.');
    }
  }
  if (typeof resumeInput === 'string') return resumeInput;
  throw new Error('Invalid resume input: must be a PDF Buffer or plain-text string.');
}

// ---------------------------------------------------------------------------
// Gemini-powered analysis
// ---------------------------------------------------------------------------
async function analyzeWithGemini(resumeText) {
  // gemini-2.5-flash-lite: lightest model available on this API key's v1beta endpoint
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });

  const prompt = `
You are an expert technical recruiter and career coach. Analyze the following resume and return a JSON object.

RESUME TEXT:
"""
${resumeText.slice(0, 12000)}
"""

Return ONLY a valid JSON object (no markdown, no explanation) with this exact structure:
{
  "skills": ["skill1", "skill2", ...],
  "suggestedRoles": ["Role Title 1", "Role Title 2", "Role Title 3", "Role Title 4", "Role Title 5"],
  "keywords": "comma separated rich keyword string combining skills, technologies, domain knowledge",
  "experienceLevel": "junior | mid | senior | lead | executive",
  "jobTitles": ["Previous Job Title 1", "Previous Job Title 2"],
  "locations": ["Location 1"],
  "summary": "2-3 sentence professional summary of the candidate"
}

Rules:
- suggestedRoles: exactly 5 specific, searchable job titles this person is a strong fit for (e.g. "Senior React Developer", not "Software Engineer")
- skills: deduplicated, specific (e.g. "React.js", "TypeScript", "REST API design")
- keywords: 20-40 terms that capture the candidate's full technical profile for semantic job matching
- experienceLevel: infer from years of experience and seniority of roles held
- Only include what is actually present in the resume — do not fabricate
`;

  const result = await model.generateContent(prompt);
  const rawText = result.response.text().trim();
  console.log('Gemini raw response (first 300 chars):', rawText.slice(0, 300));

  return extractJSON(rawText);
}

/**
 * Robustly extract a JSON object from Gemini's response text.
 * Gemini sometimes wraps JSON in markdown fences or adds prose before/after.
 * Strategy:
 *   1. Direct JSON.parse
 *   2. Strip markdown fences, try again
 *   3. Find the first {...} block with regex
 * @param {string} text
 * @returns {object}
 */
function extractJSON(text) {
  // 1. Try parsing directly (ideal case — model obeyed the prompt)
  try {
    return JSON.parse(text);
  } catch (_) {}

  // 2. Strip opening/closing markdown code fences (anywhere in the string)
  const stripped = text
    .replace(/```(?:json)?\s*/gi, '')
    .replace(/```\s*/g, '')
    .trim();
  try {
    return JSON.parse(stripped);
  } catch (_) {}

  // 3. Extract the outermost {...} block — works even with prose before/after
  const match = text.match(/\{[\s\S]*\}/);
  if (match) {
    try {
      return JSON.parse(match[0]);
    } catch (_) {}
  }

  // All strategies failed — log the raw response so we can debug
  console.error('=== Gemini raw response (JSON parse failed) ===');
  console.error(text);
  console.error('==============================================');
  throw new Error('Gemini returned a response that could not be parsed as JSON.');
}

// ---------------------------------------------------------------------------
// Fallback: basic regex extraction when Gemini is unavailable
// ---------------------------------------------------------------------------
function fallbackParse(resumeText) {
  const skillsPattern = /(?:skills|technical|expertise)[:\s]+(.*?)(?=\n|$)/gi;
  const titlesPattern = /(?:title|position|role)[:\s]+(.*?)(?=\n|$)/gi;
  const locationPattern = /(?:location|based|city)[:\s]+(.*?)(?=\n|$)/gi;

  const skills = new Set();
  const jobTitles = new Set();
  const locations = new Set();

  let match;
  while ((match = skillsPattern.exec(resumeText)) !== null) {
    match[1].split(/[,;]/).forEach(s => skills.add(s.trim().toLowerCase()));
  }
  while ((match = titlesPattern.exec(resumeText)) !== null) {
    jobTitles.add(match[1].trim());
  }
  while ((match = locationPattern.exec(resumeText)) !== null) {
    locations.add(match[1].trim());
  }

  const techKeywords = resumeText
    .toLowerCase()
    .match(/\b(?:javascript|python|java|react|node|typescript|aws|docker|kubernetes|sql|postgresql|mongodb|api|rest|graphql|machine learning|data science|devops|golang|rust|php|ruby|rails|django|vue|angular|next\.?js|express|spring|flutter|swift|kotlin)\b/gi) || [];

  const keywords = [...new Set(techKeywords)];

  return {
    skills: Array.from(skills),
    suggestedRoles: Array.from(jobTitles).slice(0, 5),
    keywords: [...keywords, ...Array.from(jobTitles)].join(', ').toLowerCase(),
    experienceLevel: 'mid',
    jobTitles: Array.from(jobTitles),
    locations: Array.from(locations),
    summary: '',
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Parse a resume and extract structured data using Gemini AI.
 * Falls back to regex parsing if Gemini is unavailable.
 * @param {string|Buffer} resumeInput
 * @returns {Promise<ResumeData>}
 */
export async function parseResume(resumeInput) {
  const resumeText = await extractText(resumeInput);

  if (!process.env.GEMINI_API_KEY) {
    console.warn('No GEMINI_API_KEY — using fallback regex parser.');
    return fallbackParse(resumeText);
  }

  try {
    console.log('Analyzing resume with Gemini AI...');
    const aiResult = await analyzeWithGemini(resumeText);
    console.log(`Gemini analysis complete. Suggested roles: ${aiResult.suggestedRoles?.join(', ')}`);
    return {
      skills: aiResult.skills ?? [],
      suggestedRoles: aiResult.suggestedRoles ?? [],
      keywords: aiResult.keywords ?? '',
      experienceLevel: aiResult.experienceLevel ?? 'mid',
      jobTitles: aiResult.jobTitles ?? [],
      locations: aiResult.locations ?? [],
      summary: aiResult.summary ?? '',
    };
  } catch (err) {
    console.error('Gemini resume analysis failed, using fallback:', err.message);
    return fallbackParse(resumeText);
  }
}
